### ISSUE TITLE
Text to speech not working on a RPI

### ISSUE THREAD

**Issue by HansLe** [ThomasTr/sonos#2]
Hi Thomas, I had some problems to get TTS working on a RPI. Today I have done some recommendations in this post:
https://www.domoticz.com/forum/viewtopic.php?f=38&t=6088&start=60#p70853

Now it's working. I hope you are willing to change the sources with this recommendations. 
BTW is not line 438 in your source of sonos.php but line 351.

Regards,
HansLe

**Comment by ThomasTr** [comment]
Hi HansLe,

of course everybody is invited to work on this together. Are you willing to do a pull request?

**Comment by HansLe** [comment]
Hi ThomasTr,

I don't know what a pull request is. Can you please explain.

**Comment by ThomasTr** [comment]
Hi HansLe,

Pull requests let you tell others about changes you've pushed to a repository on GitHub.  You can read it here: https://help.github.com/articles/using-pull-requests/

You can try it if you want. If it's to hard, i will do it for you.

**Comment by HansLe** [comment]
Hi Thomas,

There are 2 pull requests now. I tried to get one pullrequest with the two changed files but  my knowledge of this tool is not enough yet.

Regards,
Hans

**Comment by ThomasTr** [comment]
Hi Hans,

wow great, thanks for your engagement. I have merged your pull requests and released version 1.3.
